version: '3'
services:
  backend:
    restart: always
    build: .
    volumes:
      - ./:/code
    ports:
      - 9000:9000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: